/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.fame.projects.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ProjectsLangUiModule extends AbstractProjectsLangUiModule {

	public ProjectsLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
