/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.models25.projects.ide;


/**
 * Use this class to register ide components.
 */
public class ProjectsLangIdeModule extends AbstractProjectsLangIdeModule {
}
