/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.fame.projects.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.fame.projects.parser.antlr.internal.InternalProjectsLangParser;
import uk.ac.kcl.inf.fame.projects.services.ProjectsLangGrammarAccess;

public class ProjectsLangParser extends AbstractAntlrParser {

	@Inject
	private ProjectsLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalProjectsLangParser createParser(XtextTokenStream stream) {
		return new InternalProjectsLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Project";
	}

	public ProjectsLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ProjectsLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
