/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.model25.projects.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractProjectsLangScopeProvider extends DelegatingScopeProvider {
}
