/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.fame.projects.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.fame.projects.ui.internal.ProjectsActivator;

public class ProjectsLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProjectsActivator.getInstance().getInjector("uk.ac.kcl.inf.fame.projects.ProjectsLang");
	}

}
