/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.fame.projects.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.fame.projects.ui.internal.ProjectsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProjectsLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ProjectsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ProjectsActivator activator = ProjectsActivator.getInstance();
		return activator != null ? activator.getInjector(ProjectsActivator.UK_AC_KCL_INF_FAME_PROJECTS_PROJECTSLANG) : null;
	}

}
