/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.fame.projects.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ProjectsLangScopeProvider extends AbstractProjectsLangScopeProvider {

}
