/**
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.fame.projects.projectsLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Effort</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.fame.projects.projectsLang.Effort#getPerson <em>Person</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.fame.projects.projectsLang.Effort#getPercentage <em>Percentage</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.fame.projects.projectsLang.ProjectsLangPackage#getEffort()
 * @model
 * @generated
 */
public interface Effort extends EObject
{
  /**
   * Returns the value of the '<em><b>Person</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Person</em>' reference.
   * @see #setPerson(Person)
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.ProjectsLangPackage#getEffort_Person()
   * @model
   * @generated
   */
  Person getPerson();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Effort#getPerson <em>Person</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Person</em>' reference.
   * @see #getPerson()
   * @generated
   */
  void setPerson(Person value);

  /**
   * Returns the value of the '<em><b>Percentage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Percentage</em>' attribute.
   * @see #setPercentage(int)
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.ProjectsLangPackage#getEffort_Percentage()
   * @model
   * @generated
   */
  int getPercentage();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Effort#getPercentage <em>Percentage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Percentage</em>' attribute.
   * @see #getPercentage()
   * @generated
   */
  void setPercentage(int value);

} // Effort
