/**
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.fame.projects.projectsLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Project</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.fame.projects.projectsLang.Project#getTitle <em>Title</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.fame.projects.projectsLang.Project#getDescription <em>Description</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.fame.projects.projectsLang.Project#getTasks <em>Tasks</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.fame.projects.projectsLang.Project#getPeople <em>People</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.fame.projects.projectsLang.ProjectsLangPackage#getProject()
 * @model
 * @generated
 */
public interface Project extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.ProjectsLangPackage#getProject_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Project#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.ProjectsLangPackage#getProject_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Project#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.fame.projects.projectsLang.Task}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.ProjectsLangPackage#getProject_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTasks();

  /**
   * Returns the value of the '<em><b>People</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.fame.projects.projectsLang.Person}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>People</em>' containment reference list.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.ProjectsLangPackage#getProject_People()
   * @model containment="true"
   * @generated
   */
  EList<Person> getPeople();

} // Project
