/**
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.fame.projects.projectsLang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.fame.projects.projectsLang.ProjectsLangFactory
 * @model kind="package"
 * @generated
 */
public interface ProjectsLangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "projectsLang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/fame/projects/ProjectsLang";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "projectsLang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ProjectsLangPackage eINSTANCE = uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectsLangPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectImpl <em>Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectImpl
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectsLangPackageImpl#getProject()
   * @generated
   */
  int PROJECT = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__TITLE = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__TASKS = 2;

  /**
   * The feature id for the '<em><b>People</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__PEOPLE = 3;

  /**
   * The number of structural features of the '<em>Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.TaskImpl
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectsLangPackageImpl#getTask()
   * @generated
   */
  int TASK = 1;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TITLE = 0;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__START = 1;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DURATION = 2;

  /**
   * The feature id for the '<em><b>Effort</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__EFFORT = 3;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.PersonImpl
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectsLangPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.impl.EffortImpl <em>Effort</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.EffortImpl
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectsLangPackageImpl#getEffort()
   * @generated
   */
  int EFFORT = 3;

  /**
   * The feature id for the '<em><b>Person</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EFFORT__PERSON = 0;

  /**
   * The feature id for the '<em><b>Percentage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EFFORT__PERCENTAGE = 1;

  /**
   * The number of structural features of the '<em>Effort</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EFFORT_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Project <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Project
   * @generated
   */
  EClass getProject();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Project#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Project#getTitle()
   * @see #getProject()
   * @generated
   */
  EAttribute getProject_Title();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Project#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Project#getDescription()
   * @see #getProject()
   * @generated
   */
  EAttribute getProject_Description();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Project#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Project#getTasks()
   * @see #getProject()
   * @generated
   */
  EReference getProject_Tasks();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Project#getPeople <em>People</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>People</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Project#getPeople()
   * @see #getProject()
   * @generated
   */
  EReference getProject_People();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Task#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Task#getTitle()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Title();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Task#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Task#getStart()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Start();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Task#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Task#getDuration()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Duration();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Task#getEffort <em>Effort</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Effort</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Task#getEffort()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Effort();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Effort <em>Effort</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Effort</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Effort
   * @generated
   */
  EClass getEffort();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Effort#getPerson <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Person</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Effort#getPerson()
   * @see #getEffort()
   * @generated
   */
  EReference getEffort_Person();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.fame.projects.projectsLang.Effort#getPercentage <em>Percentage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Percentage</em>'.
   * @see uk.ac.kcl.inf.fame.projects.projectsLang.Effort#getPercentage()
   * @see #getEffort()
   * @generated
   */
  EAttribute getEffort_Percentage();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ProjectsLangFactory getProjectsLangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectImpl <em>Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectImpl
     * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectsLangPackageImpl#getProject()
     * @generated
     */
    EClass PROJECT = eINSTANCE.getProject();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT__TITLE = eINSTANCE.getProject_Title();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT__DESCRIPTION = eINSTANCE.getProject_Description();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT__TASKS = eINSTANCE.getProject_Tasks();

    /**
     * The meta object literal for the '<em><b>People</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT__PEOPLE = eINSTANCE.getProject_People();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.TaskImpl
     * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectsLangPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__TITLE = eINSTANCE.getTask_Title();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__START = eINSTANCE.getTask_Start();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__DURATION = eINSTANCE.getTask_Duration();

    /**
     * The meta object literal for the '<em><b>Effort</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__EFFORT = eINSTANCE.getTask_Effort();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.PersonImpl
     * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectsLangPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.fame.projects.projectsLang.impl.EffortImpl <em>Effort</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.EffortImpl
     * @see uk.ac.kcl.inf.fame.projects.projectsLang.impl.ProjectsLangPackageImpl#getEffort()
     * @generated
     */
    EClass EFFORT = eINSTANCE.getEffort();

    /**
     * The meta object literal for the '<em><b>Person</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EFFORT__PERSON = eINSTANCE.getEffort_Person();

    /**
     * The meta object literal for the '<em><b>Percentage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EFFORT__PERCENTAGE = eINSTANCE.getEffort_Percentage();

  }

} //ProjectsLangPackage
