/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.fame.projects.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.fame.projects.ProjectsLangRuntimeModule;
import uk.ac.kcl.inf.fame.projects.ProjectsLangStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ProjectsLangIdeSetup extends ProjectsLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ProjectsLangRuntimeModule(), new ProjectsLangIdeModule()));
	}
	
}
