/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.fame.projects.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractProjectsLangValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uk.ac.kcl.inf.fame.projects.projectsLang.ProjectsLangPackage.eINSTANCE);
		return result;
	}
}
