/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.fame.projects;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ProjectsLangStandaloneSetup extends ProjectsLangStandaloneSetupGenerated {

	public static void doSetup() {
		new ProjectsLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
