/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.model25.projects;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProjectsLangRuntimeModule extends AbstractProjectsLangRuntimeModule {
}
